Repository cmorten/deno-rollup, pull requests merged in 2021-05, with the labels that each got.

#34 [NO-ISSUE] Support Deno 1.10.2
  .github/CHANGELOG.md
  .github/workflows/publish-egg.yml
  .github/workflows/test.yml
  README.md
  deps.ts
  egg.json
  examples/css/README.md
  examples/helloDeno/README.md
  examples/html/README.md
  examples/image/README.md
  examples/importmap/README.md
  examples/json/README.md
  examples/livereload/README.md
  examples/postcss/README.md
  examples/serve/README.md
  examples/terser/README.md
  examples/virtual/README.md
  examples/yaml/README.md
  plugins/css/README.md
  plugins/importmap/README.md
  plugins/importmap/mod.ts
  plugins/postcss/README.md
  plugins/terser/README.md
  src/cli/build.ts
  src/cli/watch.ts
  src/ensureArray.ts
  src/error.ts
  src/logging.ts
  src/mergeOptions.ts
  src/notImplemented.ts
  src/relativeId.ts
  src/rollup-plugin-deno-resolver/denoResolver.test.ts
  src/rollup-plugin-deno-resolver/denoResolver.ts
  src/rollup-plugin-deno-resolver/ensureUrl.ts
  src/rollup-plugin-deno-resolver/exists.test.ts
  src/rollup-plugin-deno-resolver/exists.ts
  src/rollup-plugin-deno-resolver/getUrlBase.ts
  src/rollup-plugin-deno-resolver/handleUnresolvedId.ts
  src/rollup-plugin-deno-resolver/isTypescript.ts
  src/rollup-plugin-deno-resolver/loadUrl.ts
  src/rollup-plugin-deno-resolver/parse.ts
  src/rollup-plugin-deno-resolver/resolveId.ts
  src/rollup/createFilter.ts
  src/rollup/fileWatcher.ts
  src/rollup/generate.ts
  src/rollup/getDestination.ts
  src/rollup/mod.ts
  src/rollup/rollup.ts
  src/rollup/supportUrlSources.ts
  src/rollup/task.ts
  src/rollup/watch.ts
  src/rollup/watcher.ts
  src/rollup/write.ts
  test/deps.ts
  test/fixtures/hello.js
  test/fixtures/hello.ts
  test/mod.ts
  test/requireSham.ts
  version.ts
Labels: dependencies

#35 [#6] Add subset of wpt for importmap plugin
  .github/CHANGELOG.md
  README.md
  egg.json
  examples/css/README.md
  examples/helloDeno/README.md
  examples/html/README.md
  examples/image/README.md
  examples/importmap/README.md
  examples/importmap/import_map.json
  examples/json/README.md
  examples/livereload/README.md
  examples/postcss/README.md
  examples/serve/README.md
  examples/terser/README.md
  examples/virtual/README.md
  examples/yaml/README.md
  plugins/css/README.md
  plugins/importmap/README.md
  plugins/importmap/deps.ts
  plugins/importmap/mod.ts
  plugins/importmap/test/plugin.test.ts
  plugins/importmap/test/wpt.test.ts
  plugins/postcss/README.md
  plugins/terser/README.md
  version.ts
Labels: plugins, tests

#36 [NO-ISSUE] Fixes some bugs regarding css and svelte plugins
  plugins/css/mod.ts
  plugins/svelte/deps.ts
  plugins/svelte/loader.js
Labels: bug, dependencies
