Repository cmorten/deno-rollup, pull requests merged in 2021-01, with the labels that each got.

#1 fix: Deno.transpileOnly is being replaced by Deno.emit
  src/rollup-plugin-deno-resolver/denoResolver.ts
Labels: bug

#2 [NO-ISSUE] Add rollup function tests
  Makefile
  src/error.ts
  src/rollup-plugin-deno-resolver/denoResolver.ts
  src/rollup-plugin-deno-resolver/ensureUrl.test.ts
  src/rollup-plugin-deno-resolver/ensureUrl.ts
  src/rollup-plugin-deno-resolver/exists.ts
  src/rollup-plugin-deno-resolver/getUrlBase.ts
  src/rollup-plugin-deno-resolver/handleUnresolvedId.ts
  src/rollup-plugin-deno-resolver/isUrl.test.ts
  src/rollup-plugin-deno-resolver/isUrl.ts
  src/rollup-plugin-deno-resolver/resolveId.test.ts
  src/rollup-plugin-deno-resolver/resolveId.ts
  src/rollup/getDestination.ts
  src/rollup/rollup.ts
  test/compareError.ts
  test/deps.ts
  test/mod.ts
  test/optionList.ts
  test/requireSham.ts
  test/suites/README.md
  test/suites/function.test.ts
  test/toUrlString.ts
  test/utils.ts
Labels: tests

#3 [NO-ISSUE] Extend cli option support
  README.md
  deps.ts
  example/README.md
  example/src/mod.ts
  example/src/nested/random.ts
  example/src/std.ts
  src/cli/build.ts
  src/cli/cli.ts
  src/cli/environment.ts
  src/cli/getConfigs.ts
  src/cli/loadAndParseConfigFile.ts
  src/cli/loadConfigFromCommand.ts
  src/cli/printTimings.ts
  src/cli/run.ts
  src/cli/watch.ts
  src/error.ts
  src/logging.ts
  src/mergeOptions.ts
  src/rollup-plugin-deno-resolver/denoResolver.ts
  src/rollup-plugin-deno-resolver/exists.ts
  src/rollup-plugin-deno-resolver/getUrlBase.test.ts
  src/rollup-plugin-deno-resolver/getUrlBase.ts
Labels: bug, enhancement

#7 [#5] Make example work remotely
  README.md
  example/README.md
  example/rollup.config.ts
  src/rollup-plugin-deno-resolver/denoResolver.ts
  version.ts
Labels: documentation, examples

#9 [#8] Support URL sources in sourcemaps
  .github/CHANGELOG.md
  src/ensureArray.ts
  src/error.ts
  src/logging.ts
  src/mergeOptions.ts
  src/relativeId.ts
  src/rollup-plugin-deno-resolver/denoResolver.ts
  src/rollup-plugin-deno-resolver/ensureUrl.ts
  src/rollup-plugin-deno-resolver/exists.ts
  src/rollup-plugin-deno-resolver/handleUnresolvedId.ts
  src/rollup-plugin-deno-resolver/loadUrl.ts
  src/rollup-plugin-deno-resolver/parse.ts
  src/rollup/createFilter.ts
  src/rollup/fileWatcher.ts
  src/rollup/generate.ts
  src/rollup/rollup.ts
  src/rollup/supportUrlSources.ts
  src/rollup/task.ts
  src/rollup/watch.ts
  src/rollup/watcher.ts
  src/rollup/write.ts
Labels: enhancement

#12 [#10] Add `bundle.close()` to examples
  README.md
  example/rollup.build.ts
Labels: documentation, examples

#13 [#11] Support input subdirectories
  src/rollup/write.ts
Labels: bug

#14 [NO-ISSUE] Remove double resolving of source url from importer
  src/rollup-plugin-deno-resolver/denoResolver.test.ts
  src/rollup-plugin-deno-resolver/denoResolver.ts
  src/rollup-plugin-deno-resolver/getUrlBase.test.ts
  src/rollup-plugin-deno-resolver/getUrlBase.ts
  src/rollup-plugin-deno-resolver/parse.test.ts
  src/rollup-plugin-deno-resolver/parse.ts
  src/rollup-plugin-deno-resolver/resolveId.test.ts
  src/rollup-plugin-deno-resolver/resolveId.ts
Labels: bug, refactor

#16 feat: 0.7.4
  .github/CHANGELOG.md
  README.md
  deps.ts
  example/README.md
  src/rollup-plugin-deno-resolver/handleUnresolvedId.test.ts
  version.ts
Labels: bug
